language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
    - MAIN_PYTHON_VERSION="2.7"
    - MAIN_TF_VERSION="1.6.*"
  matrix:
    - TF_VERSION="1.6.*"
    - TF_VERSION="1.7.*"
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
      - cmake-data
      - libboost-python-dev
before_install:
  - pip install tensorflow==$TF_VERSION
  - pip install pyyaml
  - pip install nose2
  - |
        if [ "$TRAVIS_PYTHON_VERSION" == "$MAIN_PYTHON_VERSION" && "$TF_VERSION" == "$MAIN_TF_VERSION" ]; then
            pip install pylint==1.8.2
            pip install sphinx==1.6.7
            pip install sphinxcontrib-versioning
            pip install sphinx_rtd_theme
            pip install recommonmark
        fi
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - mkdir build && cd build
  - cmake ..
  - make
  - export PYTHONPATH="$PYTHONPATH:$PWD/third_party/OpenNMTTokenizer/bindings/python/"
  - cd ..
script:
  - nose2
  - if [ "$TRAVIS_PYTHON_VERSION" == "$MAIN_PYTHON_VERSION" && "$TF_VERSION" == "$MAIN_TF_VERSION" ]; then pylint opennmt/ bin/; fi
after_success:
  - |
        if [[ "$TRAVIS_PYTHON_VERSION" == "$MAIN_PYTHON_VERSION" && "$TF_VERSION" == "$MAIN_TF_VERSION" && -n $TRAVIS_TAG ]]; then
            eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
            openssl aes-256-cbc -K $encrypted_6389583f9019_key -iv $encrypted_6389583f9019_iv -in docs/key.enc -out docs/key -d && ssh-add docs/key
            git config --global user.email "builds@travis-ci.com"
            git config --global user.name "Travis CI"
            git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
            sphinx-versioning push -e .nojekyll docs gh-pages .
        fi
